### ISSUE TITLE
Error using genedrug API endpoint

### ISSUE THREAD

**Issue by fortuno** [sing-group/pandrugs-backend#1]
Hi there!

I am checking and getting familiar with the API endpoints for PanDrugs. When I try to query the genedrug endpoint I am not able to make it work for some reason. 

I'm probably missing something simple but I cannot see what it is. The example query I am trying is:

https://www.pandrugs.org/pandrugs-backend/api/genedrug?gene=BRCA1

Is there something wrong with that query? Am I missing something?

Thanks in advance!

**Comment by mrjato** [comment]
We are aware of this issue and it seems that there is a problem with the XML conversion, as this request work properly when converting to JSON.

We will fix this problem but, meanwhile, if you include the `Accept: application/json` header in your request, you will get the results in JSON format.

**Comment by mrjato** [comment]
This issue is the same as the https://github.com/sing-group/pandrugs-backend/issues/2 issue, that was originally posted in the https://github.com/sing-group/pandrugs-docker project.

I am closing this issue, but related updates can be followed at https://github.com/sing-group/pandrugs-backend/issues/2
